---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/posts
  label: Updates
  create: all
  match: "**/*"
  new_doc_ext: mdx
- type: directory
  path: content/pages
  label: Pages
  create: all
  match: "**/*"
  new_doc_ext: mdx
- type: heading
  label: Front Page Settings
- type: document
  path: src/@lekoarts/gatsby-theme-minimal-blog/texts/bottom.mdx
  label: Bottom Text
- type: document
  path: src/@lekoarts/gatsby-theme-minimal-blog/texts/hero.mdx
  label: Hero Text
- type: document
  path: src/@lekoarts/gatsby-theme-minimal-blog/texts/feature.mdx
  label: Featured Project
upload_dir: static/uploads
public_path: "/static/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
