---
label: Product
hide_body: false
fields:
- name: name
  type: text
  config:
    required: false
  label: Name
  description: the name of the product
- name: price
  type: number
  label: Price
  description: the price of the product
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: available
  type: boolean
  label: Available
  description: available or not available
- name: preorder
  type: boolean
  label: Preorder
  description: Is the product a preorder or in stock item?
- name: start
  type: datetime
  description: the start date of the groupbuy/preorder
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
  label: Groupbuy Start Date
  showOnly:
    field: preorder
    value: true
- name: end
  type: datetime
  label: Groupbuy End Date
  description: the end date of the groupbuy
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
  showOnly:
    field: preorder
    value: true
